name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dark-guild-girl-bot:latest
    - name: Push the Docker image
      run: docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD} && docker image push iamnzrv/dark-guild-girl-bot:latest
    
