name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Set properties
      run: echo bot.token=${{ secrets.BOT_TOKEN }} > ./src/main/resources/application.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag dark-guild-girl-bot
    - name: Push the Docker image
      run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} && docker image push iamnzrv/dark-guild-girl-bot:latest
    
