# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        java-version: '15'
        distribution: 'adopt'
    - name: Set properties
      uses: christian-draeger/write-properties@1.0.1
      with:
        path: './src/main/resources/application.properties'
        property: 'bot.token'
        value: ${BOT_TOKEN}
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
